baseURL = 'https://STIM-org.gitub.io/'
languageCode = 'ro'
title = 'Asociația ȘTIM'
theme = "hugo-universal-theme"
themesDir = "./themes"


summatyLength = 70
paginate = 10

style = "default"


[menu]

[[menu.main]]
	name = "Despre noi"
	url = "/about"
	identifier = "menu.home"
	weight = 1

#[[menu.main]]
	#name = "Donează"
	#url = "/donate"
	#weight = 2
	#identifier = "menu.donate"

[[menu.main]]
	name = "Evenimente"
	url = "/events"
	weight = 3
	identifier = "menu.events"

[[menu.main]]
	name = "Contact"
	url = "/contact"
	weight = 4
	identifier = "menu.contact"

#[[menu.main]]
	#name = "Membrii"
	#parent = "menu.home"
	#url = "/members"
	#weight = 3

[[menu.main]]
	name = "Scop"
	parent = "menu.home"
	url = "/purpouse"
	weight = 2

[[menu.main]]
	name = "Istoric"
	parent = "menu.events"
	url = "/history"
	weight = 3

#[[menu.main]]
	#name = "Pagini Personale"
	#parent = "menu.home"
	#url = "/pages"
	#weight = 4

#[[menu.main]]
	#name = "Proiecte"
	#parent = "menu.events"
	#url = "/projects"
	#weight = 1

#[[menu.main]]
	#name = "Media"
	#parent = "menu.events"
	#url = "/media"
	#weight = 2

[[menu.main]]
	name = "Olimpiade"
	parent = "menu.events"
	url = "/olimp"
	weight = 4

[[menu.main]]
	name = "Concursuri"
	parent = "menu.events"
	url = "/concursuri"
	weight = 4

[params]
	logo = "img/stim_landsc.png"
	logo_small = "img/stim_landsc.png"
	contact_url = "/contact"
	mainSections = ["members", "olimp", "projects", "concursuri"]

[params.topbar]
	enable = true
	text = """<p class="hidden-sm hidden-xs">Contact us on 0786 355 555 or contact@stimorg.com.</p>
	"""

[params.widgets]
	categories = true
	tags = true
	search = true

[params.carouselCustomers]
	items = 6
	auto_play = false
	slide_speed = 2000
	pagination_speed = 1000

[params.carouselTestimonials]
	items = 4
	auto_play = false
	slide_speed = 2000
	pagination_speed = 1000

[params.carouselHomepage]
	enable = true
	auto_play = true
	slide_speed = 2000
	pagination_speed = 1000

[[menu.topbar]]
	weight = 1
	name = "Phone"
	url = "tel:0786 355 555"
	pre = "<i class='fas fa-2x fa-phone'></i>"

[[menu.topbar]]
	weight = 2
	name = "Facebook"
	url = "https://www.facebook.com/profile.php?id=100091080968315"
	pre = "<i class='fab fa-2x fa-facebook'></i>"

[[menu.topbar]]
	weight = 3
	name = "Instagram"
	url = "https://www.instagram.com/asociatia_stim/"
	pre = "<i class='fab fa-2x fa-instagram'></i>"

[[menu.topbar]]
	weight = 5
	name = "Email"
	url = "mailto:contact@stimorg.com"
	pre = "<i class='fas fa-2x fa-envelope'></i>"

[params.see_more]
	enable = true
	icon = "far fa-file-alt"
	title = "Află mai multe"
	subtitle = "<strong>Asociația ȘTIM vrea să adune într-o comunitate pe toți foștii, actualii și viitorii olimpici naționali ai țării dar și pe profesorii ce au fost alături de ei.</strong>"
	link_url = "purpouse/"
	link_text = "Despre noi"

[params.clients]
	enable = true
	title = "Our Clients"
	subtitle = ""

#[params.recent_posts]
	#enable = true
	#title = "From our blog"
	#subtitle = "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo."
	#hide_summary = false

[params.footer.recent_posts]
	enable = true
